# Gems
gems: [jekyll-paginate]

timezone: America/Chicago
highlighter: rouge
markdown: kramdown
permalink: /post/:title
paginate: 5
paginate_path: '/blog/:num'
excerpt_separator: "\n\n\n"

title: Sollenne
email: rich@sollenne.com
description: > # ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.sollenne.com" # the base hostname & protocol for your site
twitter_username: richsollenne
github_username:  sollenne

